### ISSUE TITLE
Gear.sol vs OptimizedGear.sol

### ISSUE THREAD

**Issue by Olshansk** [ryan-foo/gear-for-cypherpunks#1]
It seems `Gear.sol` and `OptimizedGear.sol` are identical as of the [latest commit](https://github.com/ryan-foo/gear-for-cypherpunks/commit/449f3357cde3e40062c327b6d51534393c879678) when writing this message.

What is the purpose or difference between the two?

My best guess is that one was intended to import libraries from `OpenZeppelin` while the other was meant to be more verbose, but am not 100% sure.

**Comment by ryan-foo** [comment]
Thanks for the comment.

You are correct, in that they are identical right now. `Gear.sol` was indeed intended to showcase the end without the imports.

I'll change that in the next commit.
